#!/bin/sh -eu

# This is the install script for gdm when run in a privileged
# container.
#
# The host file system must be mounted at /host

cd /
PATH="/usr/bin:/usr/sbin"

if [ ! -d /host/etc ] || [ ! -d /host/proc ] || [ ! -d /host/run ]; then
    echo "gdm-install: host file system is not mounted at /host" >&2
    exit 1
fi
if [ -f /host/usr/bin/gdm ]; then
    echo "gdm-install: gdm must not be installed in the host" >&2
    exit 1
fi
if [ ! -f /host/usr/lib*/libnss_systemd.so.* ]; then
    echo "gdm-install: nss-systemd package must be installed on host system" >&2
    exit 1
fi
if [ ! -e /host/etc/nsswitch.conf ]; then
    grep -q 'passwd.*systemd' /host/usr/etc/nsswitch.conf
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
	cp /host/usr/etc/nsswitch.conf /host/etc/nsswitch.conf
	cd /host/etc
	patch -p0 -b -z .gdm-installer < /container/nsswitch.conf.patch
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
		echo "unable to create /etc/nsswitch.conf with nss-systemd enabled " >&2
    		echo "gdm-install: nss-systemd is not configured in /etc/nsswitch.conf nor /usr/etc/nsswitch.conf, check man nss-systemd " >&2
        	echo "try applying the following patch to /etc/nsswitch.conf (/usr/etc/nsswitch.conf is the umodified file) " >&2
		cat /container/nsswitch.conf.patch >&2
		exit 1
	fi
	cd -
    fi
else
	grep -q 'passwd.*systemd' /host/etc/nsswitch.conf
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
		echo "gdm-install: nss-systemd is not configured in /etc/nsswitch.conf nor /usr/etc/nsswitch.conf, check man nss-systemd " >&2
	        echo "try applying the following patch to /etc/nsswitch.conf (/usr/etc/nsswitch.conf is the umodified file) " >&2
		cat /container/nsswitch.conf.patch >&2
		exit 1
	fi
fi


# we need accountsservice on the host for now
if [ ! -f /host/usr/libexec/accounts-daemon ]; then
	echo "gdm-install: accountsservice package must be installed on host system" >&2
	exit 1
fi

# copy all dbus policies if not existing on host
for i in /usr/share/dbus-1/system.d/gdm.conf ; do
	dbus_policy=$(basename $i)
	if [ ! -e /host/$i ] && [ ! -e /host/etc/dbus-1/system.d/$dbus_policy ] ; then
		cp -av $i /host/etc/dbus-1/system.d/$dbus_policy
	fi
done

# For podman, install a systemd unit for starting on boot and userdb entries and default config files for gdm
if [ "${container:-}" = podman ]; then
    if [ ! -e /host/etc/systemd/system/gdm.service ]; then
	mkdir -p /host/etc/systemd/system/
	sed -e "s,%IMAGE%,${IMAGE},g" /container/systemd/gdm.service > /host/etc/systemd/system/gdm.service
    fi
    if [ ! -e /host/etc/userdb/gdm.user ]; then
	mkdir -p /host/etc/userdb/
	cp -avr /container/userdb/* /host/etc/userdb
    fi
    if [ ! -d /host/etc/gdm ]; then
	mkdir -p /host/etc/gdm
	cp -avr /etc/gdm/* /host/etc/gdm/
    fi
    if [ ! -e /host/etc/sysconfig/displaymanager ]; then
	cp -avr /etc/sysconfig/displaymanager /host/etc/sysconfig/
    fi
fi

