#!/bin/sh -eu

# This is the uninstall script for gdm when run in a privileged
# container.
#
# The host file system must be mounted at /host

cd /
PATH="/usr/bin:/usr/sbin"

if [ ! -d /host/etc ] || [ ! -d /host/proc ] || [ ! -d /host/run ]; then
    echo "gdm-uninstall: host file system is not mounted at /host"
    exit 1
fi

if [ "${container:-}" = podman -a -e /run/dbus/system_bus_socket ]; then
	systemctl --quiet stop gdm gdm-systemd display-manger gdm-display-manager 2> /dev/null
fi
# removing installed files
if [ "${container:-}" = podman ]; then
  chroot /host /usr/bin/systemd-tmpfiles --remove /etc/tmpfiles.d/gdm.conf
else
  systemd-tmpfiles --root=/host --remove /etc/tmpfiles.d/gdm.conf || true
fi

USERID=$(chroot /host userdbctl --output classic | grep gdm | cut -d : -f 3)
GROUPID=$(chroot /host userdbctl --output classic | grep gdm | cut -d : -f 4)
rm -fr /host/{etc/sysconfig/displaymanager,etc/systemd/system/{gdm,gdm-systemd}.service,/etc/gdm,etc/dbus-1/system.d/gdm.conf} /host/etc/userdb/{gdm.group,gdm.user,$USERID.user,$GROUPID.group} /host/etc/tmpfiles.d/gdm.conf

if [ "${container:-}" = podman -a -e /run/dbus/system_bus_socket ]; then
	chroot /host /usr/bin/systemd-sysext unmerge 2>/dev/null
	chroot /host /usr/bin/portablectl detach gdm 2>/dev/null
	systemctl --quiet try-reload-or-restart nscd
	systemctl daemon-reload
	systemctl reload dbus
	systemctl restart accounts-daemon
fi

rm -fr /host/var/lib/extensions/gdm /host/var/lib/portables/gdm

# Everything else is settings and should remain
