#!/bin/bash

TARGET=${1:-/usr/lib/userdb}
mkdir -p $TARGET
while IFS= read -r line; do 
 IFS=":"
 read -a passwd <<< "$line"
 echo { \"userName\" : \"${passwd[0]}\", \"disposition\" : \"system\", \"uid\" : ${passwd[2]}, \"gid\" :  ${passwd[3]}, \"realName\" :  \"${passwd[4]}\", \"homeDirectory\" : \"${passwd[5]}\", \"shell\" : \"${passwd[6]}\" } > "$TARGET/${passwd[0]}.user"
 ln -s "${passwd[0]}.user" "$TARGET/${passwd[2]}.user"
done < /etc/passwd


while IFS= read -r line; do 
 IFS=":"
 read -a group <<< "$line"
 if [  "${group[3]}x" != x ]; then
	 GROUP_MEMBERS=",\"members\" : [\""$(echo ${group[3]} | sed -e 's@,@\",\"@g')"\"]"
 else
	 GROUP_MEMBERS=""
 fi
 echo { \"groupName\" : \"${group[0]}\", \"gid\" : ${group[2]} "$GROUP_MEMBERS" } > "$TARGET/${group[0]}.group"
 ln -s "${group[0]}.group" "$TARGET/${group[2]}.group"
done < /etc/group
